#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BAAR.Droid.Resource", IsApplication=true)]

namespace BAAR.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth.Resource.Animation.slide_in_right = global::BAAR.Droid.Resource.Animation.slide_in_right;
			global::Xamarin.Auth.Resource.Animation.slide_out_left = global::BAAR.Droid.Resource.Animation.slide_out_left;
			global::Xamarin.Auth.Resource.Drawable.ic_arrow_back = global::BAAR.Droid.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth.Resource.Id.webview = global::BAAR.Droid.Resource.Id.webview;
			global::Xamarin.Auth.Resource.Layout.activity_webview = global::BAAR.Droid.Resource.Layout.activity_webview;
			global::Xamarin.Auth.Resource.String.title_activity_webview = global::BAAR.Droid.Resource.String.title_activity_webview;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::BAAR.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::BAAR.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::BAAR.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pbutton = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int Behaviour_Spinner = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int DebugButton = 2131230725;
			
			// aapt resource value: 0x7f08000d
			public const int EmailButton = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int Location_Spinner = 2131230732;
			
			// aapt resource value: 0x7f080003
			public const int Password_Text = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int Password_Textbox = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int Username_Text = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Username_Textbox = 2131230722;
			
			// aapt resource value: 0x7f08000e
			public const int contentFrame = 2131230734;
			
			// aapt resource value: 0x7f080007
			public const int scanButton = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int stuID = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int stuName = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int stuPic = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int textView2 = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int webview = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int student = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscanneractivitylayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscannerfragmentlayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int title_activity_webview = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
